repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 18.0.5
    values:
      - helm-values/kube-prometheus-stack.yaml
#  - name: cert-manager
#    namespace: cert-manager
#    chart: jetstack/cert-manager
#    version: v1.5.3
#    values:
#      - helm-values/cert-manager.yaml
