prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 1024Mi
      limits:
        memory: 2048Mi
kubeControllerManager:
  enabled: true
kubeScheduler:
  enabled: true
coreDns:
  enabled: true
kubeDns:
  enabled: false
grafana:
  plugins:
    - grafana-piechart-panel
  persistence:
    enabled: true
  deploymentStrategy:
    type: Recreate

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - grafana.local.io
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.local.io
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 24h
      receiver: 'slack_general'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'
    - name: slack_general
      slack_configs:
      - api_url: https://hooks.slack.com/services/XXX
        channel: '#devops-notifications'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        send_resolved: true
        username: 'cluster'
